### ISSUE TITLE
第四步没看懂，真是太不好意思了，能详细点吗

### ISSUE THREAD

**Issue by cyjcxy** [puti94/react-native-puti-pay#12]
第四步 设置 URL Scheme URL Scheme是通过系统找到并跳转对应app的设置，通过向项目中的info.plist文件中加入URL types可使用第三方平台所注册的appkey信息向系统注册你的app，当跳转到第三方应用支付后，可直接跳转回你的app。微信填写微信ID,支付宝也建议添加ap+加支付宝应用id的形式以免冲突。

指的是在info里找到URL Types，然后添加两行，dentifier和,URL Scheme应该填写什么？是填写dentifier:weixin,URL Scheme：收钱的企业微信ID还是微信平台里查到的AppID，支付宝也一样是吗？
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>weixin</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>wxf541xxxxxxxxxx</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>ap20180315xxxxxxxx</string>
			</array>
		</dict>
	</array>

还有第五步，在AppDelegate.m下加下回调，
return [RCTLinkingManager application:application openURL:url options:options];
这句出错：No known class method for selector 'application:application openURL:url options:'，
按React Native中文网上说明，改成下面的就通过了
return [RCTLinkingManager application:application openURL:url
 sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
            annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];

**Comment by cyjcxy** [comment]
已经解决了，谢谢，发现问的都是初级问题，跟react-native-puti-pay无关

**Comment by georgezouq** [comment]
@cyjcxy  怎么解决的？？
