### ISSUE TITLE
utdid与alipaySDK冲突？

### ISSUE THREAD

**Issue by hexiao-o** [puti94/react-native-puti-pay#13]
首先感谢你的开源，我这在在同时使用 [react-native-aliyun-push](https://github.com/wonday/react-native-aliyun-push)与alipaySDK冲突，查了说是utdid与alipaySDK冲突；

能帮忙看下吗？

十分谢谢

**Comment by puti94** [comment]
@hexiao-o   https://help.aliyun.com/knowledge_detail/59152.html?spm=5176.7851421.2.9.DI68G0  你好，尝试用这里提供的方法解决下。这个问题我没遇见过

**Comment by hexiao-o** [comment]
谢谢，替换了剥离UTDID的支付宝SDK就好了
