### ISSUE TITLE
升级到最新的 Xcode Version 10.2 (10E125) 提示

### ISSUE THREAD

**Issue by fannaoshaoxiang** [puti94/react-native-puti-pay#34]
Release-iphoneos/libRNPutiPay.a(AlipaySDK)
ld: 615 duplicate symbols for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

求大神查看一下，项目上线急

**Comment by puti94** [comment]
那么大胆敢升级xcode，你自己复制duplicate symbols for architecture arm64百度解决下吧

**Comment by fannaoshaoxiang** [comment]
我想哭！ 百度是 冲突？？ 实在没有明白，哪里冲突了

**Comment by fannaoshaoxiang** [comment]
大神 救救命吧！因为要提交审核，所以升级了

**Comment by fannaoshaoxiang** [comment]
方法1.查看自己项目中是否有重复命名的文件
(一般就是这个问题，如果项目中排查后，没有发现，就该项目所在的文件是否有重复命名的文件，删除一个就可以了，排查的目标一般都在报错前面列举出来了)

方法2.再查看是否在编辑#improt头文件时候，不小心把.h误写成.m
方法3.查看被编译的文件中是否有重复的（如果有文件显示红色一般是编译器没有找到的文件）。 
进入Target->Build Settings->Compile Sources下，查看是否有异常文件。
方法4.设置
Step 1: Go to TARGETS -> Build Settings -> No Common Blocks -> No

Step 2: Go to TARGETS -> Build Settings -> enable testability -> No

没有用！

**Comment by fannaoshaoxiang** [comment]
大神还是不行 ！我最后无能为力了，请大神出马解决一下

**Comment by fannaoshaoxiang** [comment]
ld: 615 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

提示又改了

**Comment by fannaoshaoxiang** [comment]
大神 libRNPutiPay.a 我试过了 静态类 出了问题

**Comment by puti94** [comment]
我这没安装最新版本也没办法试，你或许可以切回我之前的版本，手动添加ios依赖的

**Comment by fannaoshaoxiang** [comment]
收到 我已经 降回 Xcode了

**Comment by fannaoshaoxiang** [comment]
我今天晚上 
将Xcode回退到10.1 发现是可以正常编译的没有任何问题
升级到 10.2 就不行了

**Comment by puti94** [comment]
用10.1不可以提交苹果市场吗？ xcode不要着急更新，坑很多的

**Comment by fannaoshaoxiang** [comment]
感谢大神！这个坑是我太年轻了，现已经解决。已经提交审核中了

**Comment by jiasongs** [comment]
怎么解决的，我这里也是这个问题 @fannaoshaoxiang

**Comment by bocaiJs** [comment]
@jiasongs @fannaoshaoxiang 老哥 ，你们是怎么搞的呀
我也遇到这个问题了

**Comment by puti94** [comment]
@jiasongs  @bocaiJs  建议降xcode版本

**Comment by snake0git** [comment]
进入  File -> Workspace Settings 选择 Legacy Build System 就好了

**Comment by mengerzhuanyong** [comment]
> 进入 File -> Workspace Settings 选择 Legacy Build System 就好了

有效+1
