### ISSUE TITLE
支付宝支付 提示系统繁忙

### ISSUE THREAD

**Issue by bocaiJs** [puti94/react-native-puti-pay#36]
//设置	支付宝URL Schemes
        XPay.setAlipayScheme('ap2017102209453437')

因为没有数据 测试数据用的例子里的
 aliPay = () => {
        XPay.alipay('app_id=2015052600090779&biz_content=%7B%22timeout_express%22%3A%2230m%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22total_amount%22%3A%220.01%22%2C%22subject%22%3A%221%22%2C%22body%22%3A%22%E6%88%91%E6%98%AF%E6%B5%8B%E8%AF%95%E6%95%B0%E6%8D%AE%22%2C%22out_trade_no%22%3A%22IQJZSRC1YMQB5HU%22%7D&charset=utf-8&format=json&method=alipay.trade.app.pay&notify_url=http%3A%2F%2Fdomain.merchant.com%2Fpayment_notify&sign_type=RSA2&timestamp=2016-08-25%2020%3A26%3A31&version=1.0&sign=cYmuUnKi5QdBsoZEAbMXVMmRWjsuUj%2By48A2DvWAVVBuYkiBj13CFDHu2vZQvmOfkjE0YqCUQE04kqm9Xg3tIX8tPeIGIFtsIyp%2FM45w1ZsDOiduBbduGfRo1XRsvAyVAv2hCrBLLrDI5Vi7uZZ77Lo5J0PpUUWwyQGt0M4cj8g%3D',
            res => {
                console.log('回调', res);
                const {result, memo, resultStatus} = res;
                if (resultStatus === '9000') {
                    Toast.success('充值成功')
                } else {
                    Toast.fail('充值失败')
                }
            })
    };

然后提示 系统繁忙ALIN10146

请问这是集成的问题 ，还是数据的问题呢，

**Comment by puti94** [comment]
集成成功了，数据问题

**Comment by bocaiJs** [comment]
@puti94  老哥 还有个问题。 在IOS的模拟器上调用wxPay 和aliPay没有反应 是因为模拟器上没有装微信和支付宝的原因嘛

**Comment by puti94** [comment]
对

**Comment by bocaiJs** [comment]
@puti94  感谢老哥~
