### ISSUE TITLE
[android] 安卓微信支付成功后返回商家的时候APP闪退

### ISSUE THREAD

**Issue by bocaiJs** [puti94/react-native-puti-pay#37]
支付成功了， 然后点击返回商家 APP就闪退了，然后也没有回调

更新一下:ios测试也是支付没有问题，但是点击返回商家的时候不会返回到App，而是直接返回到微信的聊天页，好消息是APP没有闪退；  
支付宝是没有问题的， 能支付 有回调
1.会是微信后台设置签名的问题吗？（
后台设置了app的签名和包名，XPay.setWxId('wx5910848fd932e0ee');这一步也做了
）
2.要么就是集成参数哪里不对
3.还是APP哪里的问题
4.测试用的debug版本

有没有老哥知道 怎么排查

**Comment by bocaiJs** [comment]
@puti94  老大能帮忙瞅一眼不

**Comment by puti94** [comment]
ios没有设置 URL Schemes这个值是wxid，安卓需要连接到androidstudio看下错误日志

**Comment by bocaiJs** [comment]
@puti94 ios的 URL Schemes 设置了的。 会不会是因为微信的后台没有绑定bundle ID呢。
安卓需要连接到androidstudio看下错误日志嘛，谢啦 老哥，

**Comment by puti94** [comment]
ios还需要设置白名单，看下有没有

**Comment by bocaiJs** [comment]
@puti94  白名单是设置了的， 就是按照文档里的， 加了微信还有支付宝
