### ISSUE TITLE
无法访问IWXAPIEventHandler 找不到com.tencent.mm.opensdk.openapi.IWXAPIEventHandler的类文件

### ISSUE THREAD

**Issue by FreeHotHeart** [puti94/react-native-puti-pay#38]

**Comment by BigIdiots** [comment]
我也遇到了，有解决办法吗？项目都跑不起来了

**Comment by 18605161612** [comment]
i have the same problem

**Comment by 18605161612** [comment]
have resvled，add this "implementation 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+'" to build.gradle
