### ISSUE TITLE
AlipaySDK/AlipaySDK.h' file not found

### ISSUE THREAD

**Issue by qq326646683** [puti94/react-native-puti-pay#4]
AlipaySDK/AlipaySDK.h' file not found

**Comment by maxlxq** [comment]
解决了吗？

**Comment by songzhengxu** [comment]
这个问题，还是没解决，，

**Comment by songzhengxu** [comment]
确定已经成功链接库文件，， 但是还是报这个错

**Comment by puti94** [comment]
@songzhengxu  @qq326646683  @maxlxq  配置应该还是不对，https://github.com/puti94/RNExample 我这里有集成好的例子

**Comment by songzhengxu** [comment]
已经解决了，， 不要直接链接node_modules/react-native-puti-pay/ios_pay_lib 

而是需要把ios_pay_lib 复制到项目根目录后，再链接到项目 ，， 就可以了，
