### ISSUE TITLE
作者您好,我用了这个插件安卓的一直无法拉起,返回系统繁忙,是为什么呀.谢谢你了

### ISSUE THREAD

**Issue by luchaolulu** [puti94/react-native-puti-pay#41]
生成的订单号是没有问题的

**Comment by luchaolulu** [comment]
是支付宝支付

**Comment by puti94** [comment]
基本可以断定是安卓的签名跟蚂蚁金服的后台配置不对应

**Comment by luchaolulu** [comment]
后端生成的订单是可以在官方demo中拉起支付宝客户端的,能麻烦您和我说一下安卓这边的签名客户端这边要怎么修改呀

**Comment by puti94** [comment]
不好意思，挺久没做支付功能了，支付宝是不需要配置签名的，能详细描述下问题吗，系统繁忙应该是已经吊起支付宝了吧，支付宝提示的系统繁忙吧？

**Comment by luchaolulu** [comment]
谢谢你呀,问题已经解决了,是我自己这边设置了沙箱测试的问题,真的不好意思打扰你了
