### ISSUE TITLE
0.60 版本 编译失败

### ISSUE THREAD

**Issue by bocaiJs** [puti94/react-native-puti-pay#43]
iOS
In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
Go to node_modules ➜ react-native-puti-pay and add RNPutiPay.xcodeproj
In XCode, in the project navigator, select your project. Add libRNPutiPay.a to your project's Build Phases ➜ Link Binary With Libraries
Run your project (Cmd+R)<

根据官网提示 执行到这里
想执行看看会不会报错
![image](https://user-images.githubusercontent.com/19830233/67100730-c8843d00-f1f2-11e9-9f67-806bf83dff1b.png)

没有报错信息， 直接失败 
请问应该怎么办

**Comment by dzqlovemm112** [comment]
同样的问题，这个好像不支持pod 吗。新项目都是pod 的

**Comment by puti94** [comment]
0.60的支持已经更新上去
