### ISSUE TITLE
错误: 程序包android.support.annotation不存在 import android.support.annotation.Nullable

### ISSUE THREAD

**Issue by liuxiaofan** [puti94/react-native-puti-pay#44]
错误: 程序包android.support.annotation不存在 import android.support.annotation.Nullable
react native 0.61.2
![image](https://user-images.githubusercontent.com/8596255/67620866-2261b400-f83e-11e9-90b9-b574c4f19d40.png)

**Comment by liuxiaofan** [comment]
找到一个解决方案：https://bin.zmide.com/?p=337。

**Comment by caizhangxuan** [comment]
@liuxiaofan 有用，感谢
