### ISSUE TITLE
安卓微信支付点击没反应

### ISSUE THREAD

**Issue by lany9527** [puti94/react-native-puti-pay#5]
## 安卓微信支付配置如下:

![image](https://user-images.githubusercontent.com/19483798/34806926-caaf9ec8-f6c0-11e7-87b3-f40c6d144b1d.png)
![image](https://user-images.githubusercontent.com/19483798/34806983-11137858-f6c1-11e7-9403-d9d09f8ca246.png)

**Comment by puti94** [comment]
@lany9527  AndroidManifest文件有没有添加这个Activity呢？

**Comment by puti94** [comment]
<activity
            android:name=".wxapi.WXPayEntryActivity"
            android:exported="true"
            android:launchMode="singleTop" />
要添加例如这样的

**Comment by puti94** [comment]
`<activity
            android:name=".wxapi.WXPayEntryActivity"
            android:exported="true"
            android:launchMode="singleTop" />`
添加你自己的activity

**Comment by lany9527** [comment]
@puti94 
sorry, 漏了图片.
我已经添加了的.还是没反应. 感觉activity没被唤醒的样子.


![image](https://user-images.githubusercontent.com/19483798/34810021-d3e58986-f6d3-11e7-9cb1-ae9c0ee2c09c.png)

**Comment by puti94** [comment]
如果支付宝可以那应该集成没问题。可能要检测下是不是微信应用设置那些没有配置好，我这边自己集成是没有问题的

**Comment by lany9527** [comment]
@ puti 
### 主要是js调用那里回调函数都没有反应

**Comment by puti94** [comment]
能调用支付宝添加了wxactivity，说明配置没问题，我也不知道哪一个环节出了问题，具体可以要去原生调试下

**Comment by LANGRENDEXIAOYAO163** [comment]
这个问题有没有人解决啊  我也遇到了  我支付宝可以调起来但是微信没有反应

**Comment by puti94** [comment]
@LANGRENDEXIAOYAO163  能发下具体信息吗？ios还是android？

**Comment by puti94** [comment]
@LANGRENDEXIAOYAO163   你应该是步骤集成还是有问题，1059592160 加我QQ吧

**Comment by shiyunsheng** [comment]
是不是签名有问题？

**Comment by puti94** [comment]
只要步骤对，应该都是没有问题的，android最好打开AndroidStudio先编译下，看下是否有报错，wxapi包是不是有添加，包下面是不是有新建一个WXPayEntryActivity。AndroidManifest.xml是不是有声明这个activity。我自己按照README一步一步来集成是没有问题的。可能对不懂原生的开发者来说有点难，但我不可能把原生的知识点都列出来。如果完全按照步骤集成还是有问题，或者说README步骤需要再详细点。欢迎issues

**Comment by puti94** [comment]
如果条用方法能跳转到微信端或者支付宝。那就说明集成成功，如果支付错误那就是支付的参数有问题

**Comment by LANGRENDEXIAOYAO163** [comment]
@puti94 @shiyunsheng @lany9527 谢谢你们的回答   问题最后得到了解答  有几个地方需要注意
      1、签名的时候key一定要一定要用小写参数不能少，tradetype一定要是“APP”
      2、调用lz插件的时候参数传递一定要传递正确{
             partnerId:partnerId,
             prepayId: prepayId,
             packageValue:packageValue,
             nonceStr: nonceStr,
             timeStamp: timeStamp,
           sign: sign,}
    还有就是传递“package”一定要写成“packageValue”，再次感谢大家

**Comment by hqwlkj** [comment]
@LANGRENDEXIAOYAO163   

> _ XPay.wxPay(params,(res)=>console.log(res))有返回信息（现在是没有返回信息的）就更好

你们在回调中没有信息，你们是怎么处理回调的呢？  求教
