### ISSUE TITLE
请问我们现在的SDK里面还包含UIWebView？现在ios因为UIWebView不能上架

### ISSUE THREAD

**Issue by Hetaoweb** [puti94/react-native-puti-pay#52]
使用命令： grep -r UIWebView ../node_modules/
搜索出如下：
../node_modules//react-native/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
../node_modules//react-native/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
../node_modules//react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
Binary file ../node_modules//react-native-puti-pay/ios/libWeChatSDK.a matches
Binary file ../node_modules//react-native-puti-pay/ios/AlipaySDK.framework/AlipaySDK matches
../node_modules//metro/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
../node_modules//metro/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
Binary file ../node_modules//@0x5e/react-native-alipay/ios/libAlipaySDK.a matches

**Comment by ZeroJian** [comment]
相同问题,不知是否可更新下

**Comment by puti94** [comment]
暂时可以去微信开放平台下载最新的SDK替换之前的包，后续我更新下

**Comment by long-joan** [comment]
您好 作者 这个问题解决了么
