### ISSUE TITLE
打包安卓的时候报错   PayReactPackage

### ISSUE THREAD

**Issue by haofeng123** [puti94/react-native-puti-pay#7]
/Users/pengtaikeji/Desktop/CaiChuFang/node_modules/react-native-puti-pay/android/src/main/java/com/puti/paylib/PayReactPackage.java:15: 错误: PayReactPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class PayReactPackage implements ReactPackage {
       ^
1 个错误
:react-native-puti-pay:compileReleaseJavaWithJavac FAILED

**Comment by puti94** [comment]
在比较早的RN版本需要在PayReactPackage里面实现这个方法
 @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
